fun main() {
    print("Student Enrollment No. : ")
    var s1: String? = readLine()
    print("Student Name : ")
    var s2: String? = readLine()
    print("Student Branch : ")
    var s3: String? = readLine()
    print("Student Class : ")
    var s4: String? = readLine()
    print("Student Batch : ")
    var s5: String? = readLine()
    print("Student College Name : ")
    var s6: String? = readLine()
    print("Student University Name : ")
    var s7: String? = readLine()
    print("Student Age : ")
    var s8: String? = readLine()

    println("*")
    println("Student's Details: ")
    println("Student Enrollment No. : $s1")
    println("Student Name : $s2")
    println("Student Branch : $s3")
    println("Student Class : $s4")
    println("Student Batch : $s5")
    println("Student College Name : $s6")
    println("Student University Name : $s7")
    println("Student Age : $s8")
}